#https://learn.microsoft.com/en-us/azure/machine-learning/reference-yaml-deployment-managed-online
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: my-endpoint
model: azureml:lover:1
  #path: ../../model-1/model/
code_configuration:
  code: ../../model-1/onlinescoring/
  scoring_script: score.py
environment: 
  conda_file: ../../model-1/environment/conda.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: Standard_DS2_v2
instance_count: 1
request_settings:
  request_timeout_ms: 50000 # default is 5000
  max_concurrent_requests_per_instance: 1 # default is 1
  max_queue_wait_ms: 50000 # default is 500
