name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.24.0
  - pandas=1.5.2
  - openai=0.25.0
  - pip=21.2.4

  - pip: # these have to be here for the endpoint to work
    - azureml-defaults==1.47.0
    - inference-schema[numpy-support]==1.5
    - joblib==1.1.1
    - matplotlib==3.6.2
    - plotly==5.11.0
    - scipy==1.9.3
    - scikit-learn==1.2.0
    - tenacity==8.1.0