import { GoogleLogin } from "@react-oauth/google";
import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import { parseJwt } from "../utils/parseJwt";
import { useAuth } from "../utils/context/AuthContext";
import { Button, Divider } from "@mantine/core";
import Link from "next/link";

const Home: NextPage = () => {
  const { state, login } = useAuth();

  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="container mx-auto flex min-h-screen w-[70ch] flex-col p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          AI Search
        </h1>

        <p className="w-[80%]">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora
          quisquam explicabo modi enim quaerat mollitia similique a reiciendis
          laborum, recusandae sit nam distinctio illum culpa ducimus qui odit
          quam natus? Consequuntur harum ab optio eligendi in qui, sunt repellat
          placeat magnam, repudiandae nesciunt quidem corrupti velit, eius
          doloribus saepe beatae.
        </p>
        <Divider className="my-5"/>
        {!state.isLoggedIn ? (
          <section>
            <h4 className="my-5 text-2xl font-semibold">Sign in / register</h4>
            <GoogleLogin
              onSuccess={async (credentialResponse) => {
                const credentials = credentialResponse.credential;
                if (!credentials)
                  return alert("Could not authenticate with Google");

                try {
                  const parsed = parseJwt(credentials);

                  // TODO: get token
                  login({
                    name: parsed.name,
                    firstName: parsed.given_name,
                    email: parsed.email,
                    token: "token",
                    uid: "uid",
                  });
                } catch (e) {
                  alert(`Could not authenticate with Google (${e})`);
                }
              }}
              onError={() => {
                console.log("Login Failed");
              }}
            />
          </section>
        ) : (
          <section>
            <h4 className="my-5 text-2xl">Welcome {state.firstName}!</h4>
              <Button variant="outline" className="block"><Link href={"/projects"}>Your projects</Link></Button>
          </section>
        )}
      </main>
    </div>
  );
};

export default Home;
