import { Button } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import HeaderResponsive from "../components/Header";

import dynamic from "next/dynamic";

const PDFViewer = dynamic(() => import("../components/pdf-viewer"), {
  ssr: false
});

export default function PDF() {
  return <PDFViewer />;
}


// const Home: NextPage = () => {
//   return (
//     <>
//       <Head>
//         <title>Create T3 App</title>
//         <meta name="description" content="Generated by create-t3-app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <HeaderResponsive
//         links={[
//           { label: "My Projects", link: "/project" },
//           { label: "Sign out", link: "/signout" },
//         ]}
//       />

//       <main className="container mx-auto flex min-h-screen w-[70ch] flex-col items-center p-4">
//         <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
//           AI Search
//         </h1>

//         <p className="w-[80%]">
//           Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora
//           quisquam explicabo modi enim quaerat mollitia similique a reiciendis
//           laborum, recusandae sit nam distinctio illum culpa ducimus qui odit
//           quam natus? Consequuntur harum ab optio eligendi in qui, sunt repellat
//           placeat magnam, repudiandae nesciunt quidem corrupti velit, eius
//           doloribus saepe beatae.
//         </p>
//         <div className="flex">
//           <Button variant="outline" className="mr-4">
//             Sign up
//           </Button>
//           <Button variant="outline">Dashboard</Button>
//         </div>
//       </main>
//     </>
//   );
// };
