import { GoogleLogin } from "@react-oauth/google";
import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import { useEffect } from "react";
import useUser from "../utils/hooks/useUser";

const Home: NextPage = () => {
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="container mx-auto flex min-h-screen w-[70ch] flex-col items-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          AI Search
        </h1>

        <p className="w-[80%]">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora
          quisquam explicabo modi enim quaerat mollitia similique a reiciendis
          laborum, recusandae sit nam distinctio illum culpa ducimus qui odit
          quam natus? Consequuntur harum ab optio eligendi in qui, sunt repellat
          placeat magnam, repudiandae nesciunt quidem corrupti velit, eius
          doloribus saepe beatae.
        </p>
        <div className="">
          <h4 className="mb-5 text-center text-2xl">Sign up</h4>
          {user == null && (
            <GoogleLogin
              onSuccess={(credentialResponse) => {
                console.log(credentialResponse);
              }}
              onError={() => {
                console.log("Login Failed");
              }}
            />
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
