import { Button, Loader, TextInput } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { z } from "zod";
import Link from "next/link";
import HeaderResponsive from "../../../components/Header";

const FileCard = () => {
  return (
    <div className="flex flex-col rounded-lg bg-white p-4 shadow-lg">
      <div className="flex flex-row justify-between">
        <div className="flex flex-col">
          <h2 className="text-2xl font-bold">File name</h2>
          <p className="text-gray-500">File description</p>
          <p className="text-gray-500">File size</p>
          <p className="text-gray-500">File type</p>
        </div>
      </div>
      <div className="flex flex-row justify-end">
        <Button color="red">Delete</Button>
      </div>
    </div>
  );
};

const cards = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

const Home: NextPage = () => {
  const [searchValue, setSearchValue] = useState("");
  return (
    <>
      <Head>
        <title>Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderResponsive
        links={[
          { label: "My Projects", link: "/projects" },
          { label: "Sign up", link: "/signup" },
        ]}
      />

      <main className="container mx-auto flex min-h-screen w-[60ch] flex-col p-4">
        <section>
          <h2 className="text-left text-4xl font-extrabold leading-normal text-gray-700">
            Law search
          </h2>
          <p className="text-gray-500">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora
          </p>
        </section>
        <section className="mt-2">
          <Button variant="outline" size="xs">
            New file
          </Button>
        </section>

        <section>
          <h3 className="text-2xl">All files</h3>
          <div className="auto-responsive grid">
            {cards.map((card) => (
              <FileCard />
            ))}
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
